config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :students, only: [:index, :show, :new, :create, :edit, :update, :delete, :destroy]
end

app/models/address.rb
class Address < ApplicationRecord
  validates_presence_of :description
  validates_presence_of :street_address
  validates_presence_of :city
  validates_presence_of :state
  validates_presence_of :zip_code

  belongs_to :student
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  validates_presence_of :name
  has_many :addresses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:edit, :show, :update, :destroy]

  def index
    @students = Student.all
  end

  def show
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.create(student_params)
    @student.save

    redirect_to student_path(@student)
  end

  def edit
  end

  def update
    @student.update(student_params)

    redirect_to student_path(@student)
  end

  def destroy
    Student.destroy(params[:id])

    redirect_to students_path
  end

  private

    def student_params
      params.require(:student).permit(:name)
    end

    def set_student
      @student = Student.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enrollment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |form| %>
  <ul>
    <% @student.errors.full_messages.each do |error|%>
      <li><%= error %></li>
      <% end %>
  </ul>
  <p>
    <%= form.label :name %><br />
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/students/edit.html.erb
<h1>Edit: <%= @student.name %></h1>

<%= render partial: 'form' %>

app/views/students/index.html.erb
<h1>All Students</h1>

<% @students.each do |student| %>
  <ul>
    <li><%= link_to student.name, student_path(student), class:'student-name'%></li>
    <li><%= student.name %></li>
  </ul>
  <% end %>

<%= link_to "Add New Student", new_student_path, class: 'new-student' %>

app/views/students/new.html.erb
<%= render partial: 'form' %>

app/views/students/show.html.erb
<h1><%=  @student.name %></h1>

<%= link_to "Back to Students List", students_path %>

<%= link_to "Edit Student", edit_student_path(@student) %>

<%= link_to "Delete Student", student_path(@student), method: :delete %>

<% @student.addresses.each do |address| %>
<%= address.description %>
<%= address.street_address %>
<%= address.city %>
<%= address.state %>
Zip: <%= address.zip_code %>

<% end %>